Bean/up/readme
opensourceryclub/OpenSourcerySite pull request #17
Opened 2020-09-17 00:40 UTC by lovendatj

Updating to the readme.md

2020-09-17 20:06 UTC, DonIsaac requested changes

2020-09-17 20:06 UTC, DonIsaac commented on README.md
> +$ git clone https://github.com/opensourceryclub/OpenSourcerySite.git
This is incorrect. Contributors should for the repo (which sets their `origin` remote properly), make changes on said fork, and then submit a PR when they're done making changes.

2020-09-17 20:51 UTC, lovendatj commented
@DonIsaac correction were made. Is there anything else I should add?

2020-09-18 23:42 UTC, lovendatj reviewed
It looks good now, will add link to opensourcery website later

2020-09-21 17:46 UTC, DonIsaac approved these changes

2020-09-21 17:47 UTC, merged