Beandev
opensourceryclub/OpenSourcerySite pull request #18
Opened 2020-09-18 01:31 UTC by lovendatj

Create page component for future implementation of the project page.

Added cardType tag to each project (regular, large). Currently no SCCS styling changes.

2020-09-18 01:50 UTC, DonIsaac requested changes

2020-09-18 01:50 UTC, DonIsaac commented on README.md
> +> A collection of templates for creating applications and websites.
wot

2020-09-18 01:50 UTC, DonIsaac commented on src/components/lib/ProjectCard.tsx
> +            <div className={"card "+ cardType} style={{ height: '100%' }}>
use the `classnames` package

2020-09-18 01:50 UTC, DonIsaac commented on src/hooks/useGithubRepos.ts
> +    regular     :{type:CardType.Regular, maxChar:75},
make the card type the keys, e.g `[CardType.Regular]: 75`

2020-09-18 01:50 UTC, DonIsaac commented on src/hooks/useGithubRepos.ts
> +    cardType: string;
Why is this a prop? isn't it what's returned?

2020-09-18 02:25 UTC, lovendatj commented on src/components/lib/ProjectCard.tsx
> +            <div className={"card "+ cardType} style={{ height: '100%' }}>
How would I use the ```classnames``` for this

2020-09-21 17:45 UTC, DonIsaac commented on src/hooks/useGithubRepos.ts
> +    cardType:CardType;
This should not be here as this parameter is never used

2020-10-01 22:01 UTC, closed without merging