Fixed groupme icon
opensourceryclub/OpenSourcerySite pull request #19
Opened 2020-09-23 01:13 UTC by harmless-tech

Issue #7

2020-09-23 22:54 UTC, DonIsaac requested changes

2020-09-23 22:54 UTC, DonIsaac commented on src/components/lib/Label.tsx
> +export const Icon: FC<IconProps> = ({ fillStyle = "", icon = "", fa = "true" }) => {
default to a boolean, noy a string

2020-09-24 17:52 UTC, harmless-tech commented on src/components/lib/Label.tsx
> +export const Icon: FC<IconProps> = ({ fillStyle = "", icon = "", fa = "true" }) => {
Done

2020-10-07 17:16 UTC, DonIsaac commented
@harmless-tech what's the status of this PR?

2020-10-07 18:40 UTC, harmless-tech commented
> @harmless-tech what's the status of this PR?

This PR is done and ready to be merged.

2020-10-14 23:19 UTC, DonIsaac approved these changes

2020-10-14 23:19 UTC, merged